# Generated by Django 5.1.7 on 2025-03-27 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Middleware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('apache', 'Apache'), ('nginx', 'Nginx'), ('jboss', 'JBoss'), ('tomcat', 'Tomcat'), ('weblogic', 'WebLogic'), ('was', 'WebSphere')], max_length=32)),
                ('installed_version', models.CharField(max_length=32)),
                ('latest_version', models.CharField(max_length=32)),
                ('patched', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=128)),
                ('ip_address', models.GenericIPAddressField()),
                ('os', models.CharField(max_length=64)),
                ('group', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='PatchingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('done', 'Completed'), ('failed', 'Failed')], max_length=32)),
                ('last_run', models.DateTimeField(auto_now=True)),
                ('log', models.TextField(blank=True, null=True)),
                ('middleware', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patching.middleware')),
            ],
        ),
        migrations.AddField(
            model_name='middleware',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patching.server'),
        ),
    ]
