services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: django-backend
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./core:/app/core
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  db:
    image: postgres:14
    container_name: postgres-db
    environment:
      POSTGRES_DB: middleware
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpass
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  worker:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: celery-worker
    command: celery -A config.celery worker --loglevel=info
    volumes:
      - ./core:/app/core
    env_file:
      - .env
    depends_on:
      - backend
      - redis
      - db

volumes:
  pgdata: